server:
  port: ${PORT_GATEWAY:8080}
  
eureka:
  instance:
    health-check-url-path: /actuator/health
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8081}/eureka
    healthcheck:
      enabled: true
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://FIRST-SERVICE
        predicates:
        - Path=/employee/**
        
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
    
info:
  tags:
    environment: test
